name: Testes RESTCOUNTRIES

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-tests-Modelo-Blackbox:
    runs-on: ubuntu-22.04
    strategy:
      # não falhe todo o matrix em caso de falha
      fail-fast: false
      matrix:
        # execute cópias do job atual em paralelo
        containers: [1,  2,  3,  4,  5]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run end-to-end black box tests 🧪
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          group: "UI-Chrome"
      - name: Download the build folder
        uses: actions/download-artifact@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          group: "UI-Chrome"
          command: npm run cypress:run
  cypress-tests-Modelo-Whitebox:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run white box tests 🧪
        run: npm run jest