name: Testes RESTCOUNTRIES

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-tests-Modelo-Blackbox:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Install global dependencies 
        run: |
          npm install -g @vue/cli-service@4.5.19
          npm install -g cypress@13.6.3
          npm install -g mochawesome-merge@4.3.0
          npm install -g mochawesome-report-generator@6.2.0
          npm install -g mochawesome@7.1.3
          npm install -g moment@2.29.4 
      - name: Run end-to-end black box tests 🧪
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          command: npm run cypress:run
      - name: List Cypress videos
        run: ls -la cypress/videos
      - name: List Cypress reports
        run: ls -la cypress/reports  
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos/*.mp4
      - name: Upload Cypress HTML report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-html-report
          path: cypress/reports/*.html    
  Jest-tests-Modelo-Whitebox:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Install global dependencies
        run: |
          npm install -g jest@29.7.0
          npm install -g supertest@6.3.4
          npm install -g jest-html-reporters@3.1.7
          npm install -g moment@2.29.4
      - name: Run white box tests 🧪
        run: npm run jest
      - name: Generate Jest HTML report
        run: npx jest --reporters="default" --reporters="jest-html-reporters"
      - name: Upload Jest HTML report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: jest-html-report
          path: ./jest/reports/